package model.entity.enumeration.status;

public enum EtapaDeEnsino {

	ENSINO_FUNDAMENTAL, ENSINO_MEDIO, GRADUACAO, POS_GRADUACAO, DOUTORADO, MESTRADO, ENSINO_MEDIO_INTEGRADO_AO_TECNICO,
	ENSINO_TECNICO,
}
